p8105_hw1_wl2926
================
Wenwen Li
2023-09-21

# Problem 1

## Decribe the Dataset

Write a short description of the dataset using inline R code: \* the
variables in this dataset, including names / values of important
variables \* the size of the dataset (using nrow and ncol) \* the mean
temperature

### Size of the dataset

use nrow and ncol function

``` r
nrow(early_january_weather)
```

    ## [1] 358

``` r
ncol(early_january_weather)
```

    ## [1] 15

The dataset contains 358 observationss and 15 variables

### Variables

Getting list of variable names

``` r
colnames(early_january_weather)
```

    ##  [1] "origin"     "year"       "month"      "day"        "hour"      
    ##  [6] "temp"       "dewp"       "humid"      "wind_dir"   "wind_speed"
    ## [11] "wind_gust"  "precip"     "pressure"   "visib"      "time_hour"

Important variables may include: time_hour: Time of the measurement.
temp: Temperature. humid: Humidity.

\##use ‘skimr::skim’ function to look at the data for the first setp

``` r
skimr::skim(early_january_weather)
```

|                                                  |                       |
|:-------------------------------------------------|:----------------------|
| Name                                             | early_january_weather |
| Number of rows                                   | 358                   |
| Number of columns                                | 15                    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                       |
| Column type frequency:                           |                       |
| character                                        | 1                     |
| numeric                                          | 13                    |
| POSIXct                                          | 1                     |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                       |
| Group variables                                  | None                  |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| origin        |         0 |             1 |   3 |   3 |     0 |        1 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate |    mean |     sd |      p0 |     p25 |     p50 |     p75 |    p100 | hist  |
|:--------------|----------:|--------------:|--------:|-------:|--------:|--------:|--------:|--------:|--------:|:------|
| year          |         0 |          1.00 | 2013.00 |   0.00 | 2013.00 | 2013.00 | 2013.00 | 2013.00 | 2013.00 | ▁▁▇▁▁ |
| month         |         0 |          1.00 |    1.00 |   0.00 |    1.00 |    1.00 |    1.00 |    1.00 |    1.00 | ▁▁▇▁▁ |
| day           |         0 |          1.00 |    8.04 |   4.31 |    1.00 |    4.00 |    8.00 |   12.00 |   15.00 | ▇▇▇▇▇ |
| hour          |         0 |          1.00 |   11.53 |   6.92 |    0.00 |    6.00 |   11.50 |   17.75 |   23.00 | ▇▇▆▇▇ |
| temp          |         0 |          1.00 |   39.58 |   7.06 |   24.08 |   33.98 |   39.02 |   44.96 |   57.92 | ▃▇▇▇▁ |
| dewp          |         0 |          1.00 |   28.06 |  10.73 |    8.96 |   19.94 |   26.06 |   35.06 |   53.06 | ▃▇▆▂▃ |
| humid         |         0 |          1.00 |   65.48 |  18.95 |   32.86 |   51.34 |   61.67 |   78.68 |  100.00 | ▃▇▆▂▅ |
| wind_dir      |         5 |          0.99 |  208.19 | 115.58 |    0.00 |  140.00 |  240.00 |  290.00 |  360.00 | ▅▁▂▇▆ |
| wind_speed    |         0 |          1.00 |    8.23 |   4.61 |    0.00 |    5.75 |    8.06 |   11.51 |   24.17 | ▅▇▆▂▁ |
| wind_gust     |       308 |          0.14 |   22.53 |   3.63 |   16.11 |   19.56 |   21.86 |   25.32 |   31.07 | ▅▇▃▇▁ |
| precip        |         0 |          1.00 |    0.00 |   0.01 |    0.00 |    0.00 |    0.00 |    0.00 |    0.19 | ▇▁▁▁▁ |
| pressure      |        38 |          0.89 | 1022.52 |   5.57 | 1010.80 | 1018.30 | 1022.05 | 1027.23 | 1034.40 | ▃▇▇▇▃ |
| visib         |         0 |          1.00 |    8.52 |   3.00 |    0.12 |    9.00 |   10.00 |   10.00 |   10.00 | ▁▁▁▁▇ |

**Variable type: POSIXct**

| skim_variable | n_missing | complete_rate | min                 | max                 | median              | n_unique |
|:--------------|----------:|--------------:|:--------------------|:--------------------|:--------------------|---------:|
| time_hour     |         0 |             1 | 2013-01-01 01:00:00 | 2013-01-15 23:00:00 | 2013-01-08 12:30:00 |      358 |

There are 1 character variable, 13 numeric variables and 1 POSIXct
variable.

### the mean temperature

Using functions to get the mean temperature

``` r
mean(early_january_weather$temp, na.rm=TRUE)
```

    ## [1] 39.58212

The mean of the temperature is 39.58212.

## Make a scatterplot of temp(y) vs time_hour(x)

``` r
set.seed(1)
scatter_plot<-ggplot(early_january_weather,aes(x=time_hour,y=temp,color=humid))+geom_point()
print(scatter_plot)
```

![](p8105_hw1_wl2926_files/figure-gfm/unnamed-chunk-5-1.png)<!-- --> \##
Export Scatterplot

``` r
ggsave("sctter_plot.pdf", plot = scatter_plot,height = 4, width = 6)
```

# Problem 2

Create a data frame comprised of:

-   a random sample of size 10 from a standard Normal distribution
-   a logical vector indicating whether elements of the sample are
    greater than 0
-   a character vector of length 10
-   a factor vector of length 10, with 3 different factor “levels”

## Create data frame

``` r
set.seed(1)
rnorm_sample = rnorm(10, sd = 1)
print(rnorm_sample)
```

    ##  [1] -0.6264538  0.1836433 -0.8356286  1.5952808  0.3295078 -0.8204684
    ##  [7]  0.4874291  0.7383247  0.5757814 -0.3053884

## a logical vector indicating whether elements of the sample are greater than 0

``` r
set.seed(1)
vec_logical <- rnorm_sample > 0
print(vec_logical)
```

    ##  [1] FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE

## a character vector of length 10

``` r
vec_char = c("uni", "cute", "westie", "puppy", "girl","white","little","small","dog","really")
print(vec_char)
```

    ##  [1] "uni"    "cute"   "westie" "puppy"  "girl"   "white"  "little" "small" 
    ##  [9] "dog"    "really"

## a factor vector of length 10, with 3 different factor “levels”

``` r
vec_factor = factor(vec_char, levels = c("uni", "cute", "westie"))
print(vec_factor)
```

    ##  [1] uni    cute   westie <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  
    ## Levels: uni cute westie

## Create the dataframe

``` r
df <- data.frame(
  rnorm_sample = rnorm_sample,
  vec_logical = vec_logical,
  vec_char = vec_char,
  vec_factor = vec_factor
)
```

## Calculate the mean of each variable using pull from the dataframe

``` r
mean(rnorm_sample)
```

    ## [1] 0.1322028

``` r
mean(vec_logical)
```

    ## [1] 0.6

``` r
mean(vec_char)
```

    ## Warning in mean.default(vec_char): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

``` r
mean(vec_factor)
```

    ## Warning in mean.default(vec_factor): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

### Load necessary libraries

``` r
library(tidyverse)
mean_rnorm_sample <- mean(pull(df, rnorm_sample))
mean_vec_logical <- mean(pull(df, vec_logical))
mean_vec_char <- mean(pull(df, vec_char))
```

    ## Warning in mean.default(pull(df, vec_char)): argument is not numeric or
    ## logical: returning NA

``` r
mean_vec_factor <- mean(pull(df, vec_factor))
```

    ## Warning in mean.default(pull(df, vec_factor)): argument is not numeric or
    ## logical: returning NA

It only works for numeric or bool variables; some variable cannot be
calculated.

## applies the as.numeric function

``` r
mean_rnorm_sample <- mean(pull(df, rnorm_sample))
mean_vec_logical <- mean(as.numeric(pull(df, vec_logical)))
mean_vec_char <- mean(as.numeric(pull(df, vec_char)))
```

    ## Warning in mean(as.numeric(pull(df, vec_char))): NAs introduced by coercion

``` r
mean_vec_factor <- mean(as.numeric(pull(df, vec_factor)))

# Print the means
print("Mean of rnorm_sample:")
```

    ## [1] "Mean of rnorm_sample:"

``` r
print(mean_rnorm_sample)
```

    ## [1] 0.1322028

``` r
print("Mean of vec_logical:")
```

    ## [1] "Mean of vec_logical:"

``` r
print(mean_vec_logical)
```

    ## [1] 0.6

``` r
print("Mean of vec_char:")
```

    ## [1] "Mean of vec_char:"

``` r
print(mean_vec_char)
```

    ## [1] NA

``` r
print("Mean of vec_factor:")
```

    ## [1] "Mean of vec_factor:"

``` r
print(mean_vec_factor)
```

    ## [1] NA

For the logical vector (vec_logical), as.numeric will convert TRUE to 1
and FALSE to 0.For the character vector (vec_char), as.numeric will
attempt to convert characters to numeric values. If it can’t make a
meaningful conversion (most cases), it will result in NA (Not Available)
for those elements.For the factor vector (vec_factor), as.numeric will
convert the underlying numerical representation of the factor levels.
Each factor level is internally represented by integers.
